weights = {
    "female": {
        "skin_tone": {
            "female_skin_1": 1,
            "female_skin_2": 1,
            "female_skin_3": 1,
            "female_skin_4": 1,
            "female_skin_5": 1,
            "female_skin_6": 1,
            "female_skin_7": 1,
            "female_skin_8": 1,
            "female_skin_9": 1,
        },
        "hairstyle": {
            "female_hairstyle_1": 2,
            "female_hairstyle_2": 2,
            "female_hairstyle_3": 2,
            "female_hairstyle_4": 2,
            "female_hairstyle_5": 2,
            "female_hairstyle_6": 2,
            "female_hairstyle_7": 2,
            "female_hairstyle_8": 2,
            "female_hairstyle_9": 2,
            "female_hairstyle_10": 2,
            "female_hairstyle_11": 2,
            "female_hairstyle_12": 2,
            "female_hairstyle_13": 2,
            "female_hairstyle_14": 2,
            "female_hairstyle_15": 2,
            "female_hairstyle_16": 2,
            "female_hairstyle_17": 2,
            "female_hairstyle_18": 2,
            "none": 1,
        },
        "attire": {
            "female_attire_1": 1,
            "female_attire_2": 1,
            "female_attire_3": 1,
            "female_attire_4": 1,
            "female_attire_8": 1,
            "female_attire_5": 1,
            "female_attire_6": 1,
            "female_attire_7": 1,
            "female_attire_9": 1,
            "female_attire_10": 1,
            "female_attire_11": 1,
            "female_attire_12": 1,
            "female_attire_13": 1,
            "female_attire_14": 1,
            "female_attire_15": 1,
            "female_attire_16": 1,
            "female_attire_17": 1,
            "female_attire_18": 1,
            "female_attire_19": 1,
            "female_attire_20": 1,
            "female_attire_21": 1,
            "female_attire_22": 1,
            "female_attire_23": 1,
            "female_attire_24": 1,
            "female_attire_25": 1,
            "female_attire_26": 1,
            "female_attire_27": 1,
            "female_attire_28": 1,
            "female_attire_29": 1,
            "female_attire_30": 1,
            "female_attire_31": 1,
            "female_attire_32": 1,
            "female_attire_33": 1,
            "female_attire_34": 1,
            "female_attire_35": 1,
            "female_attire_36": 1,
        },
        "accessory": {
            "astra_pack": 1,
            "jupitergold_chain": 1,
            "white_pearrl_neclace": 1,
            "none": 5,
        },
        "headgear": {
            "amethyst_shades": 5,
            "astra_helmet_spike": 1,
            "astra_cap": 5,
            "astrahelmet": 1,
            "blackasmask": 1,
            "earthrelic_shades": 5,
            "gob_mask": 5,
            "mask": 1,
            "obsidian_shades": 5,
            "silver_sodalite_shades": 5,
            "none": 10,
        },
        "back_accessory": {
            "bluflame_sword": 1,
            "gravity_board": 1,
            "none": 5,

        }
    },


    "male": {
        "skin_tone": {
            "male_skin_0": 1,
            "male_skin_1": 4,
            "male_skin_2": 4,
            "male_skin_3": 4,
            "male_skin_4": 4,
            "male_skin_5": 4,
            "male_skin_6": 4,
            "male_skin_7": 4,
            "male_skin_8": 4,
            "male_skin_9": 4,
            "male_skin_10": 4,
            "male_skin_11": 4,
            "male_skin_12": 4,
        },
        "hairstyle": {
            "male_hairstyle_1": 2,
            "male_hairstyle_2": 2,
            "male_hairstyle_3": 2,
            "male_hairstyle_4": 2,
            "male_hairstyle_5": 2,
            "male_hairstyle_6": 2,
            "male_hairstyle_7": 2,
            "male_hairstyle_8": 2,
            "male_hairstyle_9": 2,
            "male_hairstyle_10": 2,
            "male_hairstyle_11": 2,
            "male_hairstyle_12": 2,
            "male_hairstyle_13": 2,
            "male_hairstyle_14": 2,
            "male_hairstyle_15": 2,
            "none": 1,
        },
        "attire": {
            "male_attire_1": 5,
            "male_attire_2": 5,
            "male_attire_3": 5,
            "male_attire_4": 5,
            "male_attire_5": 5,
            "male_attire_6": 5,
            "male_attire_7": 5,
            "male_attire_8": 5,
            "male_attire_9": 5,
            "male_attire_10": 5,
            "male_attire_11": 2,
            "male_attire_12": 5,
            "male_attire_13": 5,
            "male_attire_14": 5,
            "male_attire_15": 5,
            "male_attire_16": 5,
            "male_attire_17": 5,
            "male_attire_18": 5,
            "male_attire_19": 5,
            "male_attire_20": 5,
            "male_attire_21": 5,
            "male_attire_22": 5,
            "male_attire_23": 5,
            "male_attire_24": 2,
            "male_attire_25": 2,
            "male_attire_26": 5,
            "male_attire_27": 5,
            "male_attire_28": 5,
            "male_attire_29": 5,
            "male_attire_30": 5,
            "male_attire_31": 5,
            "male_attire_32": 2,
            "male_attire_33": 2,
            "male_attire_34": 2,
            "male_attire_35": 5,
            "male_attire_36": 5,
            "male_attire_37": 5,
            "male_attire_38": 5,
            "none": 1,
        },
        "accessory": {
            "astra_gold": 1,
            "astra_silver": 1,
            "astra_bronze": 1,
            "astra_pack": 1,
            "none": 5,
        },
        "headgear": {
            "astra_cap": 5,
            "blackasspke_red": 2,
            "focus_mask": 2,
            "helmetenticls": 2,
            "mech_had": 1,
            "memask": 3,
            "obsidian_shades": 5,
            "punkhelmet": 2,
            "whyeemaskt": 3,
            "male_headgear_1": 5,
            "male_headgear_2": 5,
            "male_headgear_3": 5,
            "male_headgear_4": 5,
            "male_headgear_5": 2,
            "male_headgear_6": 2,
            "male_headgear_7": 2,
            "male_headgear_8": 2,
            "male_headgear_9": 5,
            "none": 10,
        },
        "back_accessory": {
            "dragon_flame_sword": 1,
            "gravity_board": 1,
            "none": 5,
        },
    },


    "background": {
        "abstract_nebula": 5,
        "aurora": 5,
        "black_hole_vortex": 5,
        "milky_mountains": 2,
        "nebula": 5,
        "planets_and_stars": 5,
        "spiral_vortex": 2,
        "split_moon": 5,
        "star_system": 5,
        "sun_cloud": 2,
    },

    "frame": {
        "amalfitan_azure": 10,
        "candy_conifer": 10,
        "carbon_fiber": 7,
        "gold": 3,
        "interstellar": 10,
        "koi": 10,
        "kraken": 6,
        "proton": 10,
        "silver_polish": 10,
        "system_shock": 10,
    }
}
