weights = {
    "male": {
        "skin_tone": {
            "astra skin 0": 1,
            "astra skin 1": 4,
            "astra skin 2": 4,
            "astra skin 3": 4,
            "astra skin 4": 4,
            "astra skin 5": 4,
            "astra skin 6": 4,
            "astra skin 7": 4,
            "astra skin 8": 4,
            "astra skin 9": 4,
            "astra skin 10": 4,
            "astra skin 11": 4,
            "astra skin 12": 4,
        },
        "hairstyle": {
            "astra hairstyle 1": 2,
            "astra hairstyle 2": 2,
            "astra hairstyle 3": 2,
            "astra hairstyle 4": 2,
            "astra hairstyle 5": 2,
            "astra hairstyle 6": 2,
            "astra hairstyle 7": 2,
            "astra hairstyle 8": 2,
            "astra hairstyle 9": 2,
            "astra hairstyle 10": 2,
            "astra hairstyle 11": 2,
            "astra hairstyle 12": 2,
            "astra hairstyle 13": 2,
            "astra hairstyle 14": 2,
            "astra hairstyle 15": 2,
            "none": 1,
        },
        "attire": {
            "astra attire 1": 5,
            "astra attire 2": 5,
            "astra attire 3": 5,
            "astra attire 4": 5,
            "astra attire 5": 5,
            "astra attire 6": 5,
            "astra attire 7": 5,
            "astra attire 8": 5,
            "astra attire 9": 5,
            "astra attire 10": 5,
            "astra attire 11": 2,
            "astra attire 12": 5,
            "astra attire 13": 5,
            "astra attire 14": 5,
            "astra attire 15": 5,
            "astra attire 16": 5,
            "astra attire 17": 5,
            "astra attire 18": 5,
            "astra attire 19": 5,
            "astra attire 20": 5,
            "astra attire 21": 5,
            "astra attire 22": 5,
            "astra attire 23": 5,
            "astra attire 24": 2,
            "astra attire 25": 2,
            "astra attire 26": 5,
            "astra attire 27": 5,
            "astra attire 28": 5,
            "astra attire 29": 5,
            "astra attire 30": 5,
            "astra attire 31": 5,
            "astra attire 32": 2,
            "astra attire 33": 2,
            "astra attire 34": 2,
            "astra attire 35": 5,
            "astra attire 36": 5,
            "astra attire 37": 5,
            "astra attire 38": 5,
            "none": 1,
        },
        "accessory": {
            "astra accessory 2": 1,
            "astra accessory 3": 1,
            "astra accessory 4": 1,
            "astra pack": 1,
            "none": 5,
        },
        "headgear": {
            "AstraCap": 5,
            "blackasspke red": 2,
            "focus mask": 2,
            "helmetenticls": 2,
            "IMG-2971": 5,
            "IMG-3376": 5,
            "IMG-3385": 5,
            "IMG-3397": 5,
            "IMG-4122": 5,
            "mech had": 1,
            "memask": 3,
            "obsidian shades": 5,
            "punkhelmet": 2,
            "whyeemaskt": 3,
            "IMG-4101": 2,
            "IMG-4102": 2,
            "IMG-4103": 2,
            "IMG-4104": 2,
            "none": 10,
        },
        "back_accessory": {
            "DragonFlame sword": 1,
            "gravity board": 1,
            "none": 5,
        },
    },



    "female": {
        "skin_tone": {
            "astra skin 1": 1,
            "astra skin 2": 1,
            "astra skin 3": 1,
            "astra skin 4": 1,
            "astra skin 5": 1,
            "astra skin 6": 1,
            "astra skin 7": 1,
            "astra skin 8": 1,
            "astra skin 9": 1,
        },
        "hairstyle": {
            "astra hairstyle 1": 2,
            "astra hairstyle 2": 2,
            "astra hairstyle 3": 2,
            "astra hairstyle 4": 2,
            "astra hairstyle 5": 2,
            "astra hairstyle 6": 2,
            "astra hairstyle 7": 2,
            "astra hairstyle 8": 2,
            "astra hairstyle 9": 2,
            "astra hairstyle 10": 2,
            "astra hairstyle 11": 2,
            "astra hairstyle 12": 2,
            "astra hairstyle 13": 2,
            "astra hairstyle 14": 2,
            "astra hairstyle 15": 2,
            "astra hairstyle 16": 2,
            "astra hairstyle 17": 2,
            "astra hairstyle 18": 2,
            "none": 1,
        },
        "attire": {
            "astra attire 1": 1,
            "astra attire 2": 1,
            "astra attire 3": 1,
            "astra attire 4": 1,
            "astra attire 8": 1,
            "astra attire 5": 1,
            "astra attire 6": 1,
            "astra attire 7": 1,
            "astra attire 9": 1,
            "astra attire 10": 1,
            "astra attire 11": 1,
            "astra attire 12": 1,
            "astra attire 13": 1,
            "astra attire 14": 1,
            "astra attire 15": 1,
            "astra attire 16": 1,
            "astra attire 17": 1,
            "astra attire 18": 1,
            "astra attire 19": 1,
            "astra attire 20": 1,
            "astra attire 21": 1,
            "astra attire 22": 1,
            "astra attire 23": 1,
            "astra attire 24": 1,
            "astra attire 25": 1,
            "astra attire 26": 1,
            "astra attire 27": 1,
            "astra attire 28": 1,
            "astra attire 29": 1,
            "astra attire 30": 1,
            "astra attire 31": 1,
            "astra attire 32": 1,
            "astra attire 33": 1,
            "astra attire 34": 1,
            "astra attire 35": 1,
            "astra attire 36": 1,
        },
        "accessory": {
            "astra pack": 1,
            "Jupitergold chain": 1,
            "white pearrl neclace": 1,
            "none": 5,
        },
        "headgear": {
            "Amethyst shades": 5,
            "astra helmet spike": 1,
            "AstraCap": 5,
            "Astrahelmet": 1,
            "blackasmask": 1,
            "Earthrelic shades": 5,
            "gob mask": 5,
            "mask": 1,
            "obsidian shades": 5,
            "silver sodalite shades": 5,
            "none": 10,
        },
        "back_accessory": {
            "bluflame sword": 1,
            "gravity board": 1,
            "none": 5,

        }
    },



    "background": {
        "astra_background_1": 10,
        "astra_background_2": 17,
        "astra_background_3": 17,
        "astra_background_4": 17,
        "astra_background_5": 17,
        "astra_background_6": 5,
        "astra_background_7": 17,
        "astra_background_8": 17,
        "astra_background_9": 17,
        "astra_background_10": 17,
    },

    "frame": {
        "astra_frame_1": 10,
        "astra_frame_2": 17,
        "astra_frame_3": 17,
        "astra_frame_4": 17,
        "astra_frame_5": 17,
        "astra_frame_6": 5,
        "astra_frame_7": 17,
        "astra_frame_8": 17,
        "astra_frame_9": 17,
        "astra_frame_10": 17,
    }
}
